In [3]:
#importing numpy library 
import numpy as np
print(np.__version__)

2.2.6


In [ ]:
#1d array (vector)
#a=np.array([1,2,3,4,5])
#print(a)
#a.shape

#2d array(matrix)
#b=np.array([[1,2,3],[4,5,6]])
#print(b)
#b.shape

#3d array(tensor)
c=np.array([[[1,2],[4,5]],[[7,8],[9,10]]])
print(c)
c.shape

In [ ]:
  #converting any data type into numpy array eg float,boolean,scomplex etc(dtype function)
a=np.array([1.5,2,3,],dtype=float)
b=np.array(["a","c"],dtype=str)
c=np.array([0,2,4],dtype=bool)   
d=np.array([1.+2.j,0],dtype=complex)

print(d)



In [33]:
#get homogenous array of range(similar to pythonng range function)
#arange(initial,final,step)
np.arange(2,10,2)


array([2, 4, 6, 8])

In [ ]:
#converting vector into nd array
#reshape(rows,columns)
a=np.arange(2,18,2).reshape(2,2,2)
b=np.arange(1,28).reshape(3,3,3)


In [ ]:
#initiaising arrays in ones, zeros,random ,identity matrix
a=np.ones((3,3))
print(a)
b=np.zeros((2,3))
print(b)
c=np.random.random((4,3))
print(c)

d=np.identity(3)
print(d)

In [ ]:
#genrate liner space (start,end,no.of elements),here each element is qui distance from other 
a=np.linspace(-10,10,10)
print(a)

array attributes


In [99]:
a1= np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)


In [ ]:
#ndim
a3.ndim
#shape (give elememt in each dim)
a2.shape
#size(total elements)
a3.size

#relation 
len(a1.shape)==a1.ndim
a2.size==a2.shape[0]*a2.shape[1]

#itesize(memory accoupied by item),int32=4,int64=8,float=8
a2.itemsize

#dtype(gives data type)
a3.dtype

# astype (changing datatype)
#chnaging datatype from int64 to float32
a3.astype(np.int32) 

array operations
1.scalar 
2.vector


In [116]:
a1=np.arange(1,10).reshape(3,3)
a2=np.arange(10,19).reshape(3,3)
a2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
#scalar operation
a1+1
a1-1
a1*2
a1/2
a1**2
#relation(check elementwise then give bool matrix)
a1>5
a1==5
a1!=5


In [ ]:
#vector operation (operation take place in each element of array)
a1+a2
a1-a2
a1*a2
a1/a2
a1**a2
a1>a2
a1==a2
a1!=a2

array function

In [150]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a2=np.random.random((4,3))
a2=np.round(a2*100)
a3=np.random.random((3,4))
a3=np.round(a3*100)

In [140]:
#max,min,sum,prod
# axis=0 means col and axis =1 means row
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)
np.max(a1,axis=0)#maximum about col
np.min(a1,axis=1)#minimum about row
np.sum(a1,axis=1)#sum about row
np.prod(a1,axis=0)#product about col


#mean,median,standard deviation,variance
np.mean(a1)
np.median(a1,axis=1)
np.var(a1,axis=0)

array([ 33.55555556, 198.22222222, 112.88888889])

In [157]:
#dot product
a1.shape#(3,3)
a2.shape#(4,3)
a3.shape#(3,4)
if a1.shape[1]==a2.shape[0]:
    print(np.dot(a1,a2))
else:
    print("not possible")


if a1.shape[1]==a3.shape[0]:
    print(np.dot(a1,a3))
else:
    print("not possible")


not possible
[[ 5510.  4658.  8349.  2681.]
 [ 3183.   742.  7608.  2237.]
 [ 7684.  6154. 11976.  3754.]]


In [163]:
#log
np.log(a1)
#exponential
np.exp(a1)
#round
b=np.random.random((3,3))*100
np.round(b)
np.floor(b)
np.ceil(b)

array([[89., 43., 99.],
       [56., 81., 39.],
       [ 2., 35., 62.]])

Array indexing  

In [31]:
a1=np.arange(10)
a2=np.arange(9).reshape(3,3)
a3=np.arange(8).reshape(2,2,2)
#indexing for vector
for i in range(len(a1)):
    a1[i]

a1[0]=10
a1[-1]

#indexing for 2d array or matrix
for i in range(a2.shape[0]):
    for j in range(a2.shape[1]):
        a2[i][j]

a2[0,1]
#indexing tensor
#array[matrix no -1,row-1,col-1]
a3[1,0,1]=100
a3



array([[[  0,   1],
        [  2,   3]],

       [[  4, 100],
        [  6,   7]]])

array slicing 


In [79]:
print(a1)
print(a2)
a3=np.arange(27).reshape(3,3,3)
a3[2,2,2]=100

print(a3)

[10  1  2  3  4  5  6  7  8  9]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[[  0   1   2]
  [  3   4   5]
  [  6   7   8]]

 [[  9  10  11]
  [ 12  13  14]
  [ 15  16  17]]

 [[ 18  19  20]
  [ 21  22  23]
  [ 24  25 100]]]


In [ ]:
#1d array[initial index:final index:step]
a1[-5:-1]
a1[2:8:2]

#2d array[initial row:final row:step,initial col:final col:step]
a2[0,:]#printing first row
a2[:,1]#printing  second col
a2[1:,1:3]
a2[::2,::2]
a2[:2,:]
a2[1,::2]

#3d array[initial matrix:final matrix:step,initial row:final row:step,initial col:final col:step]

a3[0,0,:]#first row  of first matrix
a3[0,:,0]#first col of first matrix
a3[:,0,:] # first row of every matrix
a3[:,:,0] #first col of every matrix

a3[1,:,1]
a3[2,1:,1:]
a3[:,::2,::2]
a3[::2,0,::2]


array([[ 0,  2],
       [18, 20]])

In [ ]:
#iteration by np.nditer(array) for n dimension array instead of nested loop 
for i in np.nditer(a3):
    i

#tranpose
np.transpose(a2)
a3.T
#ravel(covert n dim array into 1 dim array)
a2.ravel()
a3.ravel()
#to find index of element in n dim
#eg 100th element in (6,7,8)
i=np.unravel_index(100,(6,7,8))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
       100])

stacking and spliting  of array 
1. horizontal stacking
 2x2 + 2x2 = 2x4(col inc)

2. vertical stacking 
2x2+ 2x2= 4x2(row inc)

3. horizontal spliting 
 divided the coln in n equal parts

4.vertical split
divide the row into n equal parts


In [102]:
#horizontal
#np.hstack((a1,a2,a3..))
a1=np.arange(9).reshape(3,3)
a2=np.arange(9,18).reshape(3,3)
a3=np.hstack((a1,a2))

#vertical stack
#np.vstack((a1,a2,a3..))
a4=np.vstack((a1,a2))

#hsplit
#print(a3)
np.hsplit(a3,3)

#vsplit
print(a4)
np.vsplit(a4,3)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]