numpy
tricks


In [1]:
import numpy as np

In [56]:
#sorting 
a=np.random.randint(1,100,15)
b=np.random.randint(1,100,24).reshape(6,4)
print(b)
np.sort(b,axis=0,kind='mergesort')
print(a)
#reversing
np.sort(a)[::-1] #reverse sorting
np.flip(a)# reverse the array without sorting
np.flip(b,axis=1)# reverse the array without sorting


[[13 89  2  9]
 [30 20 46  1]
 [73  5  6 53]
 [89  9 51 24]
 [93 26 79 27]
 [70  9 20 76]]
[35 38 94 30 58 87 12 45 66 61 86 15 65 29  9]


array([[ 9,  2, 89, 13],
       [ 1, 46, 20, 30],
       [53,  6,  5, 73],
       [24, 51,  9, 89],
       [27, 79, 26, 93],
       [76, 20,  9, 70]], dtype=int32)

In [40]:
#append
np.append(a,[1,2,3])
np.append(b,np.reshape([1,2,3,4],(1,4)),axis=0)

#concatenate
a=np.random.randint(1,100,24).reshape(6,4)
c=np.random.randint(1,100,24).reshape(6,4)
np.concatenate((a,c),axis=1)

#unique give uniquievalues from multiple elements
a=np.array([1,1,1,1,2,2,2,2,3,3,4,5,6])
np.unique(a)#array([1, 2, 3, 4, 5, 6])

#expand to convert into row vector and colmn vector
np.shape(a)#(13,)
np.expand_dims(a,axis=1).shape #(13,1)coln vector
np.expand_dims(a,axis=0).shape #(1,13)row vector

#where return index of array where given codn satisy 
print(b)
np.where(b>57)
#replace 
np.where(b>57,1,0)

#argmax/argmin return index of max value on axis and array
np.argmax(b,axis=0) #index pf max value about coln
np.argmin(b,axis=1) #index of min value about row

[[ 7 89 42 91]
 [50 17 10 85]
 [93 57 78 11]
 [ 1 57 34 61]
 [40 70 41 66]
 [56 64 58 79]]


array([0, 2, 3, 0, 0, 0])

In [ ]:
#cummulative sum 
a
np.cumsum(a)
b
np.cumsum(b,axis=1)

#cummulative product
b
np.cumprod(b,axis=0)


#percentile
a
np.percentile(a,100)

#histogram gives you element betwwen range
np.histogram(a,[0,2,4,6])
  
#correlation coefficient
a=np.random.randint(1,100,4).reshape(2,2)
b=np.random.randint(1,100,4).reshape(2,2)
np.corrcoef(a,b)

#to chck multiple element in array
a=np.array([1,2,3,4,55,56,67,90,54,34])
a[np.isin(a,[1,54,9])]


#put chaneg multiple element in array
np.put(a,[0,1],[3,56])#it permanently change  the array
a
#delete 
np.delete(a,[0,1,2])# delete the indicies


array([ 4, 55, 56, 67, 90, 54, 34])

In [60]:
#set functions

a=np.array([1,2,3,4,5,6])
b=np.array([4,5,6,7,8,9])
#union 
np.union1d(a,b)
#intersection
np.intersect1d(a,b)
#set difference
np.setdiff1d(a,b)
#set symmetric difference
np.setxor1d(a,b)



#clip to keep element in ranf min ele turn to min and max ele turn to max
a=np.array([1,2,3,4,5,6,7,8,9])
np.clip(a,a_min=3,a_max=6)

array([3, 3, 3, 4, 5, 6, 6, 6, 6])