In [1]:
import numpy as np

In [4]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
a=int(input("enter the no"))
b=int(input("enter the no"))
c=np.arange(a*b).reshape(a,b)
print(c)
#avg of array
print(c.mean())



[[0 1 2]
 [3 4 5]
 [6 7 8]]
4.0


In [13]:

def matrix(a,b):
    c=np.ones(a*b).reshape(a,b)
    c[1:-1,1:-1]=0
    print(c)
matrix (2,2)

[[1. 1.]
 [1. 1.]]


In [18]:
a=np.linspace(0,1,12)
b=a[1:-1]
print(b)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [19]:
a=np.eye(3,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [22]:
r1=np.arange(5)
m=np.vstack((r1,r1,r1,r1,r1))
print(m)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
a=np.random.randint(1,101,size=(10,2))
p=np.array([2,3])
distance=np.sqrt(np.sum((a-p)**2,axis=1)).astype(int)
print(a)
print(distance)


In [34]:
a=np.arange(336).reshape(6,7,8)
i=np.unravel_index(100,(6,7,8))
print(i)


(np.int64(1), np.int64(5), np.int64(4))


In [68]:
a=np.random.randint(-10,10,size=(1,10))
a=a.flatten().astype(float)
print(a)
a[::-1]


[ 3.  0.  0.  7.  0. -3.  5. -5. -5.  2.]


array([ 2., -5., -5.,  5., -3.,  0.,  7.,  0.,  0.,  3.])

In [69]:
#softmax function
#exp(x)/sum(exp(x))
def softmax(x):
    p=np.exp(x)
    q=sum(p)
    return p/q
x=[1,2,3,4]
print(softmax(x))

[0.0320586  0.08714432 0.23688282 0.64391426]


In [71]:
def date(start,end):
   y1,d1,m1=map(int,start.split("-"))
   y2,d2,m2=map(int,end.split("-"))
   if y1!=y2:
      print("year arnt same")
   else:
      
    s=np.datetime64(start)
    d=np.datetime64(end)
    return np.arange(s,d+1,dtype='datetime64[D]') 
   

print(date("2022-01-01","2022-01-10"))
      
      

['2022-01-01' '2022-01-02' '2022-01-03' '2022-01-04' '2022-01-05'
 '2022-01-06' '2022-01-07' '2022-01-08' '2022-01-09' '2022-01-10']


In [81]:
a=np.arange(9).reshape(3,3)
b=np.mean(a,axis=1)
c=a-b
c

array([[-1., -3., -5.],
       [ 2.,  0., -2.],
       [ 5.,  3.,  1.]])

In [89]:
a=np.arange(9).reshape(3,3)
a[a%2==1]=-1
print(a)

[[ 0 -1  2]
 [-1  4 -1]
 [ 6 -1  8]]


In [96]:
a=np.random.randint(1,10000,size=40).reshape(8,5)
print(a)
#select alternate col of array
print(a[:,::2])
#normalise array
p=a-np.min(a)
q=np.max(a)-np.min(a)
print(p/q)


[[  29 9922 2577 8489  610]
 [9447 2036 9264 4310 9044]
 [2428 9006 9000 4711 4304]
 [4654 6388 3229 1885 2340]
 [8198 5173 4018 4110 1325]
 [5985 6897 3246 9777 5406]
 [8008 7462 6281 2098 1868]
 [2253 8345 4713 1842 5956]]
[[  29 2577  610]
 [9447 9264 9044]
 [2428 9000 4304]
 [4654 3229 2340]
 [8198 4018 1325]
 [5985 3246 5406]
 [8008 6281 1868]
 [2253 4713 5956]]
[[0.         1.         0.25755585 0.85515011 0.05872839]
 [0.95198625 0.20287072 0.93348833 0.43273021 0.91125038]
 [0.24249469 0.90740928 0.90680279 0.47326392 0.43212372]
 [0.46750227 0.64277772 0.32346103 0.1876074  0.23359951]
 [0.82573537 0.51996361 0.40321439 0.4125139  0.13100172]
 [0.60204185 0.69422824 0.32517942 0.98534317 0.54351562]
 [0.80652987 0.75133933 0.63196199 0.20913777 0.18588901]
 [0.22480542 0.84059436 0.47346609 0.18326089 0.59911048]]


In [110]:
a=np.arange(10)
n=np.random.randint(9)
def nlarg(a,n):
    b=np.sort(a)
    return b[-n]
print(a,n)
print(nlarg(a,n))

[0 1 2 3 4 5 6 7 8 9] 6
4


In [124]:
#patern 
a=np.array([1,2,3])
c=np.repeat(a,3)
b=np.tile(a,3)
np.concatenate((c,b))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])