sukudo
board 9x9
rules
1. the digit 1-9 appear once in every row
2. the digit 1-9 appear once in every coln
3. the digit 1-9 appear once in every 3x3 grid





In [ ]:
import numpy as np
# suduko generator

# Fill a 3x3 diagonal box
def fill_box(board, row, col):
    nums = np.random.choice(np.arange(1, 10), size=9, replace=False).reshape(3,3)
    board[row:row+3, col:col+3] = nums

# Step 1: Fill diagonal boxes
def fill_diagonal(board):
    for i in range(0, 9, 3):
        fill_box(board, i, i)

# Step 3: Remove numbers
def remove_cells(board, count):
    flat_idx = np.random.choice(81, size=count, replace=False)
    for idx in flat_idx:
        r = idx // 9
        c = idx % 9
        board[r, c] = 0

# Full generator
def generate_sudoku(remove_count=45):
    board = np.zeros((9,9), dtype=int)

    fill_diagonal(board) 
    remove_cells(board, remove_count) 

    return board



[[6 0 0 0 0 0 0 0 0]
 [9 0 8 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0]
 [0 0 0 6 4 2 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 6 7 0]]


In [ ]:
#predefined
board=np.array([[2,0,0,5,0,7,0,0,0],
        [0,0,6,2,3,0,1,0,0],
        [7,5,3,6,0,0,0,4,8],
        [0,0,0,8,0,0,4,5,1],
        [3,0,0,0,6,0,9,0,2],
        [0,8,5,0,2,0,0,3,0],
        [5,0,1,0,0,9,6,0,0],
        [0,4,9,7,0,0,0,0,3],
        [8,2,7,0,0,6,0,9,0],])
print(np.shape(board))



(9, 9)


In [5]:
#finding first empty blank row wise

def empty(board):
    pos = np.where(board == 0)
    if pos[0].size == 0:
        return None
    return pos[0][0], pos[1][0]#give first empty index

#rules
#rule1:check if num is in row
def vrow(board,row,num):
    return num not in board[row]

#rule2:check if num is in col
def vcol(board,col,num):
    return num not in board[:,col]

#rule3:check if num is in 3x3 grid  
def vbox(board,row,col,num):
    brow=(row//3)*3
    bcol=(col//3)*3
    box=board[brow:brow+3,bcol:bcol+3]#sub matrix
    return num not in box

#valid all
def isvalid(board,row,col,num):
    return(vrow(board,row,num) and vcol(board,col,num) and vbox(board,row,col,num) )

In [6]:
#backtracking
def solve(board):
    emty=empty(board)
    if emty is None:
        return True  #solved
    
    row,col=emty
    for num in range(1,10):
        if isvalid(board,row,col,num):
            board[row][col]=num

            if solve(board):
                return True
            
            board[row][col]=0

    return False

In [ ]:

b=generate_sudoku()
print("sudoku problem\n",b,"\n")
if solve(b):
    print("solved:\n",b)
else:
    print("No solution")
